# Generated by Django 6.1.1 on 2026-10-02 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_pharmacyapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyworker',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('pharmacist', 'Pharmacist')], default='pharmacist', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pharmacyworker',
            constraint=models.UniqueConstraint(fields=('user', 'pharmacy'), name='unique_pharmacy_worker'),
        ),
    ]
