import { LogIn } from "lucide-react";
import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { apiErrorMessage } from "../api/axios";
import AuthLayout from "../components/AuthLayout";
import FormField from "../components/FormField";
import Button from "../components/ui/Button";
import useAuth from "../context/useAuth";

export default function LoginPage() { const { t } = useTranslation(); const [form, setForm] = useState({ username: "", password: "" }); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); async function submit(event) { event.preventDefault(); setError(""); setSubmitting(true); try { await login(form); navigate(location.state?.from?.pathname || "/", { replace: true }); } catch (requestError) { setError(apiErrorMessage(requestError, t("auth.invalid", { defaultValue: "Неверное имя пользователя или пароль." }))); } finally { setSubmitting(false); } } return <AuthLayout eyebrow={t("auth.welcome", { defaultValue: "С возвращением" })} title={t("auth.loginTitle", { defaultValue: "Войти в PharmaMap" })} description={t("auth.loginDescription", { defaultValue: "Откройте бронирования, сообщения аптек и уведомления о наличии." })}><form onSubmit={submit} className="space-y-5">{location.state?.registered && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{t("auth.accountCreated", { defaultValue: "Аккаунт создан. Теперь войдите." })}</p>}<FormField label={t("auth.usernameOrEmail", { defaultValue: "Имя пользователя или email" })} id="username" autoComplete="username" required value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><FormField label={t("auth.password", { defaultValue: "Пароль" })} id="password" type="password" autoComplete="current-password" required value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} />{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button type="submit" size="lg" className="w-full" disabled={submitting}><LogIn className="size-4" />{submitting ? t("auth.loggingIn", { defaultValue: "Входим…" }) : t("nav.login")}</Button><p className="text-center text-sm text-slate-500">{t("auth.noAccount", { defaultValue: "Нет аккаунта?" })} <Link className="font-bold text-teal-700 hover:underline" to="/register">{t("auth.createAccount", { defaultValue: "Создать бесплатно" })}</Link></p></form></AuthLayout>; }
