import { AtSign, Bell, CalendarCheck, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { mediaUrl } from "../api/axios";
import PageHeader from "../components/PageHeader";
import Avatar from "../components/ui/Avatar";
import { Card, CardContent } from "../components/ui/Card";
import useAuth from "../context/useAuth";

export default function ProfilePage() {
  const { user } = useAuth();
  return <div className="page-shell py-10 pb-28 sm:py-14"><PageHeader eyebrow="Личный кабинет" title="Ваш профиль" description="Контактные данные и быстрый доступ к важным разделам PharmaMap." /><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="overflow-hidden"><div className="h-28 bg-teal-800 soft-grid" /><CardContent className="relative px-6 pb-7"><Avatar src={user.avatar ? mediaUrl(user.avatar) : undefined} fallback={user.username?.slice(0, 2).toUpperCase()} className="-mt-12 size-24 border-4 border-white text-2xl shadow-lg" /><h2 className="mt-4 text-2xl font-extrabold tracking-tight text-slate-950">{user.username}</h2><p className="mt-1 text-sm text-slate-500">Участник PharmaMap</p><span className="mt-4 inline-flex items-center gap-2 rounded-full bg-teal-50 px-3 py-1.5 text-xs font-bold text-teal-800"><ShieldCheck className="size-4" />{user.role === "pharmacist" ? "Фармацевт" : "Пользователь"}</span></CardContent></Card><div className="space-y-6"><Card><CardContent className="p-6"><h3 className="text-lg font-extrabold text-slate-950">Контактные данные</h3><dl className="mt-5 grid gap-3 sm:grid-cols-2"><ProfileItem icon={AtSign} label="Email" value={user.email || "Не указан"} /><ProfileItem icon={Phone} label="Телефон" value={user.phone || "Не указан"} /></dl></CardContent></Card><div className="grid gap-3 sm:grid-cols-3"><QuickLink to="/reservations" icon={CalendarCheck} title="Мои брони" text="Статусы заказов" /><QuickLink to="/chats" icon={MessageCircle} title="Сообщения" text="Диалоги с аптеками" /><QuickLink to="/notifications" icon={Bell} title="Уведомления" text="Важные события" /></div></div></div></div>;
}
function ProfileItem({ icon: Icon, label, value }) { return <div className="rounded-2xl bg-slate-50 p-4"><dt className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><Icon className="size-4 text-teal-600" />{label}</dt><dd className="mt-2 break-all font-semibold text-slate-800">{value}</dd></div>; }
function QuickLink({ to, icon: Icon, title, text }) { return <Link to={to} className="focus-ring group rounded-[1.25rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-teal-200 hover:shadow-lg"><Icon className="size-5 text-teal-700" /><h3 className="mt-6 font-extrabold text-slate-900 group-hover:text-teal-800">{title}</h3><p className="mt-1 text-xs text-slate-500">{text}</p></Link>; }
