# Generated by Django 6.1.1 on 2026-10-01 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacymedicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='pharmacymedicine',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'medicine'), name='unique_pharmacy_medicine'),
        ),
    ]
